name: Terraform Plan and Apply

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  terraform:
    runs-on: ubuntu-latest  # Definindo o ambiente para rodar no Ubuntu

    steps:
      # Passo 1: Verificar o repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Configurar AWS CLI com os Secrets
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # Passo 3: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5  # Defina a versão do Terraform que você deseja usar

      # Passo 4: Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # Passo 5: Rodar Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="db_master_username=${{ secrets.DB_MASTER_USERNAME }}" -var="db_master_password=${{ secrets.DB_MASTER_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}"

      # Passo 6: Rodar Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="db_master_username=${{ secrets.DB_MASTER_USERNAME }}" -var="db_master_password=${{ secrets.DB_MASTER_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}"

